[package]
name = "rvv-playground"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rvv-as"
path = "src/rvv_as.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
